# These are supported funding model platforms

github: [Ovyerus] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ko_fi: capuccino # Replace with a single Ko-fi username
custom: [
    "https://paypal.me/chinodesuuu",
    "https://paypal.me/notvsaucemichael",
    "https://liberapay.com/Ovyerus/"",
  ] # Replace with a single custom sponsorship URL
