engines:
  eslint:
    enabled: true
    config: .eslintrc
  duplication:
    enabled: false
    config:
      languages:
      - javascript
      - typescript
  fixme:
      enabled: true
ratings:
  paths:
  - "lib/**.ts"