plugins:
  editorconfig:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-5"
    ignore_warnings: true
    extensions:
      - .ts
  duplication:
    enabled: false
  nodesecurity:
    enabled: true
