# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    tags:
      - '**'

jobs:
  publish-npm:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Get Dependencies
      run: npm i -SD

    - name: Publish
      run: npm publish
      env: # More info about the environment variables in the README
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings

  publish-github:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
        node-version: ${{ matrix.node-version }}

    - name: Get Dependencies
      run: npm i -SD

    - name: Publish
      run: npm publish
      env: # More info about the environment variables in the README
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # You need to set this in your repo settings
